export const AVAILABILITY_CONSTANTS = {
  MIN_SERVICE_NAME_LENGTH: 3,
  MAX_SERVICE_NAME_LENGTH: 50,
  SERVICE_NAME_REGEX: /^[a-zA-ZÀ-ÿ0-9\s\-_]+$/,
  TIME_REGEX: /^(0[0-9]|1[0-9]|2[0-3]):00$/,
  DEFAULT_TIMEZONE: "America/Sao_Paulo",
};
